package com.example.topwisepos.emv;

public enum TransactionResultCode {
    APPROVED_BY_OFFLINE,
    APPROVED_BY_ONLINE,
    DECLINED_BY_OFFLINE,
    DECLINED_BY_ONLINE,
    DECLINED_BY_TERMINAL_NEED_REVERSE,
    ERROR_TRANSACTION_CANCEL,
    ERROR_TRANSACTION_TIMEOUT,
    ERROR_UNKNOWN,
}
